version: "3"

services:
  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
    depends_on: 
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile 
    ports:
      - 3000:3000
    networks:
      - my-network

  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile 
    ports:
      - 3001:3001
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
