name: Test SSH to EC2

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initial SSH Connection
        uses: tiyee/action-ssh@release
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_NAME }}
          privatekey: ${{ secrets.VM_KEY }}
          port: ${{ secrets.PORT }}
          command: |
            whoami
            ls -al
            
