name: Test SSH to EC2

on:
  push:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test SSH Connection
        env:
          KEY: ${{ secrets.VM_KEY }}
          HOSTNAME: ${{ secrets.HOST_NAME }}
          IP: ${{ secrets.HOST }}
        run: |
          echo "$KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${HOSTNAME}@{IP}

          if [ $? -eq 0 ]; then
            echo "SSH connection successful!"
          else
            echo "SSH connection failed!"
            exit 1
          fi
