name: Full cicd 

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initial SSH Connection
        uses: appleboy/ssh-action@v1.0.0
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOSTNAME }}
          key: ${{ secrets.VM_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            PROJECT_DIR='CowDevOps'
            PROJECT_REPO='https://github.com/htrungngx/CowDevOps.git'
            if [ ! -d "$PROJECT_DIR" ]; then
                echo "$PROJECT_DIR directory not found. Cloning repository..."
                git clone $PROJECT_REPO
                cd $PROJECT_DIR
            else
                echo "$PROJECT_DIR directory found. Pulling latest changes..."
                cd $PROJECT_DIR
                git pull
            fi
            git stash
            chmod +x deploy.sh
            ./deploy.sh


        