name: Test SSH to EC2

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_NAME }}
          key: ${{ secrets.VM_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al
